services:
  xpfarm:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data
      - ./screenshots:/app/screenshots
      # - ./.env:/app/.env 
    environment:
      - GIN_MODE=release
    restart: unless-stopped
