// Package model defines the canonical Finding and NormalizedGroup types shared
// across all normalization sub-packages. It has zero XPFarm-internal imports
// so every other package in the normalization tree can import it without cycles.
package model

import (
	"crypto/rand"
	"fmt"
	"time"
)

// Severity constants — every adapter must map its own severity scale into these.
const (
	SeverityInfo     = "info"
	SeverityLow      = "low"
	SeverityMedium   = "medium"
	SeverityHigh     = "high"
	SeverityCritical = "critical"
)

// Finding is the canonical security finding that all scanner adapters produce.
// Every field except Source, Target, Title, and Severity is optional.
type Finding struct {
	// ID is a random UUID-v4 string assigned by the adapter.
	ID string `json:"id"`

	// Source is the scanner that produced this finding (nuclei, nmap, semgrep, gitleaks).
	Source string `json:"source"`

	// Target is the scanned hostname, IP address, or repository URL.
	Target string `json:"target"`

	// Location is where the issue was found — a URL, file path, or function name.
	Location string `json:"location"`

	Title       string `json:"title"`
	Description string `json:"description"`

	// Severity is one of the SeverityXxx constants above.
	Severity string `json:"severity"`

	// CWE is set by the adapter (if available) or by the CWE enricher.
	// Format: "CWE-89"
	CWE string `json:"cwe"`

	// CVE is set by the adapter when the finding maps to a known vulnerability.
	// Format: "CVE-2021-44228"
	CVE string `json:"cve"`

	// CVSS is the NVD base score (0–10), populated by the CVSS enricher.
	CVSS *float64 `json:"cvss"`

	// EPSS is the FIRST.org exploitation probability (0–1), populated by the EPSS enricher.
	EPSS *float64 `json:"epss"`

	// KEV is true when the CVE appears in CISA's Known Exploited Vulnerabilities catalog.
	KEV bool `json:"kev"`

	// Evidence is a short snippet: the matching HTTP request, vulnerable line, or secret match.
	Evidence string `json:"evidence"`

	// Raw holds the unmodified scanner output that produced this finding.
	Raw map[string]any `json:"raw"`

	// Fingerprint is a SHA-256 hash of (target + location + CWE/CVE + evidence).
	// Generated by the dedupe package after enrichment.
	Fingerprint string `json:"fingerprint"`

	Tags      []string  `json:"tags"`
	Timestamp time.Time `json:"timestamp"`
}

// NormalizedGroup aggregates findings that share the same grouping key
// (CWE, CVE, Severity, and Target).
type NormalizedGroup struct {
	// GroupID is a SHA-256 hash of (cwe + cve + severity + target).
	GroupID  string    `json:"group_id"`
	CWE      string    `json:"cwe"`
	CVE      string    `json:"cve"`
	Severity string    `json:"severity"`
	Target   string    `json:"target"`
	Findings []Finding `json:"findings"`
}

// NewID generates a random UUID v4 string.
func NewID() string {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		// crypto/rand failure is extraordinarily rare; fall back to timestamp
		return fmt.Sprintf("finding-%d", time.Now().UnixNano())
	}
	b[6] = (b[6] & 0x0f) | 0x40 // version 4
	b[8] = (b[8] & 0x3f) | 0x80 // variant bits
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x",
		b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

// NormalizeSeverity maps any scanner-specific severity string into one of the
// SeverityXxx constants, defaulting to "info" on unknown input.
func NormalizeSeverity(raw string) string {
	switch raw {
	case "critical", "CRITICAL":
		return SeverityCritical
	case "high", "HIGH", "ERROR":
		return SeverityHigh
	case "medium", "MEDIUM", "WARNING", "moderate", "MODERATE":
		return SeverityMedium
	case "low", "LOW", "NOTE":
		return SeverityLow
	default:
		return SeverityInfo
	}
}
